{% set name = "louvain" %}
{% set version = "0.7.0" %}
{% set md5 = "45b9d353e5cbd2e5f1f70f15152e1f28" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  # the main dependency 'igraph' is not windows ready yet
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - igraph
    - python-igraph
  run:
    # We need to include setuptools have access to the pkg_resources,
    # see https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources
    - setuptools
    - python
    - igraph
    - python-igraph

test:
  imports:
    - igraph
    - louvain

about:
  home: https://github.com/vtraag/louvain-igraph
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Implementation of the Louvain algorithm for various methods for use with igraph in python.
  description: |
    This package implements the louvain algorithm in C++ and
    exposes it to python. It relies on (python-)igraph for it to
    function. Besides the relative flexibility of the
    implementation, it also scales well, and can be run on graphs
    of millions of nodes (as long as they can fit in memory).
    The core function is find_partition which finds the optimal
    partition using the louvain algorithm for a number of
    different methods.

extra:
  recipe-maintainers:
    - vgauthier
