travis:
  secure:
    BINSTAR_TOKEN: DfPOut3WRJkbka+42ZAtP3P3w/O+g9dC5xkXxNpv2N4tTn9+yQ/qgaL1qePCeBK/R6oKsazAhqanKN0OthFCM+xIhF7v2u21EixVWJuNam6CrZVM2WFQkiQThVniHSRQrHIE8RjCT6+FNjnH4g2hl5NBeksC8/su1XOCuLEXQPNuigQbdRy+tF+c8zYo0aiFH+hGkEVQ7Ko2t86a46PTbNZkqqvNPuG/7PiDWAzS55F0egcqdpiPt+v8YN32j+j6oAUB73EhB+x3sOwcQ+pZ4B527dhI3o7e93LhTSkVIEpg/xi6gdrS5dHUIg7eVSmLQPfll49itM4ZGu/Hy7NO0e2EOx6L/HQniCWcez2DIdZou9acLU2Iu2oQXysq1PU21iIi7rgZW3W+Ee++35/ZW68Q/iC8XROmDDN7fJL+jKslBHQrmfv6LJemp4YEvywmN6AS3xnpzCTBKCS1YNrOFmxbm39k4cIw2ovaTCHC5EDGzzT/OPdvNy86fL4iXxcBcwYkknax0ycb5jmh/GJ6AMshKRHORjlFtm5sLNhKI2YCUqyDV46qS/CtcDXcJpcP01MgbVF2Rq0DEn5vxS61R3Gl8kecvNOSF2vljuJXfMoXUkhiHP/3hxLTUMsEjcxPra551Ikcw2PzkNrk+LYyeLV2qJtbn9Fm7ajVTLgck2c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
